version: '3.8'

services:

  postgres:
    container_name: dnai-andrew-postgres
    image: docker.io/postgres:alpine3.20
    env_file:
      - env/postgres.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - postgres_network
    restart: always

  spring:
    container_name: dnai-andrew-spring
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./env/spring.env
    ports:
      - "8080:8080"
    networks:
      - postgres_network
    depends_on:
      - postgres

volumes:
  postgres-data:
    driver: local

networks:
  postgres_network:
    name: postgres_network
