/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package nss.be.messages.model

import nss.be.messages.model.Chat

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * list of chat IDs
 *
 * @param chatName 
 * @param chat 
 */


data class ChatsGet200ResponseInner (

    @Json(name = "chatName")
    val chatName: kotlin.String? = null,

    @Json(name = "chat")
    val chat: Chat? = null

) {


}

