/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package nss.be.messages.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Chat object
 *
 * @param type Type of the chat
 * @param id ID of the chat
 */


data class Chat (

    /* Type of the chat */
    @Json(name = "type")
    val type: Chat.Type,

    /* ID of the chat */
    @Json(name = "id")
    val id: java.util.UUID? = null

) {

    /**
     * Type of the chat
     *
     * Values: PRIVATE,GROUP
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "PRIVATE") PRIVATE("PRIVATE"),
        @Json(name = "GROUP") GROUP("GROUP");
    }

}

